### ISSUE TITLE
[BUG] On Windows, downloaded file not closed after download ends

### ISSUE THREAD

**Issue by Jojain** [antoine-peartree/TGVmax_mapper#1]
Error when uploading TGVmax destinations

Traceback : 
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\me\Downloads\TGVmax_mapper-master\tgvmax_mapper\user_interface.py", line 136, in start_data_updt_cb
    self.download_data(OPENDATA_URL, CHUNK_SIZE, CSV_CUT, USELESS_COLUMNS)
  File "C:\Users\me\Downloads\TGVmax_mapper-master\tgvmax_mapper\user_interface.py", line 109, in download_data
    handle = open(csv_path, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'resources/cut_tgvs.csv'

`

**Comment by antoine-peartree** [comment]
As cut_tgvs.csv is the file downloaded from SNCF opendata, it doesn't need to previously exist.
However the "resources" directory path might be wrong. Did you launch the app from the root directory ?

**Comment by Jojain** [comment]
The launching directory was indeed wrong however another bug appears when I launch it from the root directory :

Wait... 68%
Wait... 69%
Wait... 70%
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "tgvmax_mapper\user_interface.py", line 136, in start_data_updt_cb
    self.download_data(OPENDATA_URL, CHUNK_SIZE, CSV_CUT, USELESS_COLUMNS)
  File "tgvmax_mapper\user_interface.py", line 127, in download_data
    os.remove(csv_path)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'resources/cut_tgvs.csv'

**Comment by antoine-peartree** [comment]
I'm personally using Ubuntu or MacOS and never had this issue. I will try on a Windows VM soon.

**Comment by antoine-peartree** [comment]
Thanks, bug fixed into c7af5cba3c57e8df74e22b5ea9a3b33caa1afda3
